kollus:
  domain: kr.kollus.com
  version: 0
  language_key: korean
  service_account:
    key : key
    api_access_token: api_access_token
    custom_key: custom_key
  play_options:
    expire_time: 86400 # 1day

